import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Withdrawal } from './entities/withdrawal.entity';
import { CreateWithdrawDto } from './dto/create-withdraw.dto';
import { User } from '../users/entities/user.entity';
import { PackageRequestsService } from '../package-requests/package-requests.service';
import { PackageRequest } from '../package-requests/entities/package-request.entity';
import { UsersService } from '../users/users.service';

@Injectable()
export class WithdrawalsService {
  constructor(
    @InjectRepository(Withdrawal)
    private readonly withdrawalRepository: Repository<Withdrawal>,
    private readonly packageRequestsService: PackageRequestsService,
    private readonly usersService: UsersService,
  ) {}

  async createWithdrawal(user: User, dto: CreateWithdrawDto) {
    const w = this.withdrawalRepository.create({
      user,
      amount: dto.amount,
      source: dto.source,
      notes: dto.notes,
    });

    return await this.withdrawalRepository.save(w);
  }

  async findByUser(user: User) {
    return await this.withdrawalRepository.find({
      where: { user: { id: user.id } },
      order: { createdAt: 'DESC' },
    });
  }

  // Compute balances from approved package requests.
  async getBalances(user: User) {
    try {
      const requests: PackageRequest[] = await this.packageRequestsService.findByUser(user);
      const now = new Date();
      let earnings = 0;

      for (const r of requests) {
        if (r.status !== 'Approved') continue;

        const reviewedAt = r.reviewedAt ?? r.createdAt;
        if (!reviewedAt) continue;

        const rateMatch = String(r.profitRate).match(/([0-9]+(?:\.[0-9]+)?)\s*%/);
        const dailyRate = rateMatch ? Number(rateMatch[1]) : 0;

        const durMatch = String(r.duration).match(/([0-9]+)\s*/);
        const durationDays = durMatch ? Number(durMatch[1]) : 0;

        const ms = Math.max(0, now.getTime() - new Date(reviewedAt).getTime());
        const elapsedDays = Math.floor(ms / (1000 * 60 * 60 * 24));
        const applicableDays = durationDays > 0 ? Math.min(elapsedDays, durationDays) : elapsedDays;

        const accrued = Number(r.amount) * (dailyRate / 100) * applicableDays;
        earnings += accrued;
      }

      // compute referral bonus: 5% of earnings generated by referred users
      let totalRefEarnings = 0;
      try {
        const referredUsers = await this.usersService.findByReferrer(user.id);
        for (const refUser of referredUsers) {
          const refRequests = await this.packageRequestsService.findByUser(refUser);
          let refEarnings = 0;
          for (const r of refRequests) {
            if (r.status !== 'Approved') continue;
            const reviewedAt = r.reviewedAt ?? r.createdAt;
            if (!reviewedAt) continue;
            const rateMatch = String(r.profitRate).match(/([0-9]+(?:\.[0-9]+)?)\s*%/);
            const dailyRate = rateMatch ? Number(rateMatch[1]) : 0;
            const durMatch = String(r.duration).match(/([0-9]+)\s*/);
            const durationDays = durMatch ? Number(durMatch[1]) : 0;
            const ms = Math.max(0, now.getTime() - new Date(reviewedAt).getTime());
            const elapsedDays = Math.floor(ms / (1000 * 60 * 60 * 24));
            const applicableDays = durationDays > 0 ? Math.min(elapsedDays, durationDays) : elapsedDays;
            refEarnings += Number(r.amount) * (dailyRate / 100) * applicableDays;
          }
          totalRefEarnings += refEarnings;
        }
      } catch (err) {
        totalRefEarnings = 0;
      }

      const bonus = Number((totalRefEarnings * 0.05).toFixed(2));

      return {
        earnings: Number(earnings.toFixed(2)),
        bonus,
      };
    } catch (err) {
      return { earnings: 0, bonus: 0 };
    }
  }
}
